name: Md.Common
on:
  push:
    branches:
      - main
    paths:
      - 'Md.Common/**'
  workflow_dispatch:
jobs:
  buildAndPublishNuget:
    uses: MichaelDiers/shared-workflows/.github/workflows/dotnet-nuget.yaml@main
    with:
      projectName: Md.Common
      solutionFolder: Md.Common
    secrets:
      nugetAuthToken: ${{ secrets.NUGET_AUTH_TOKEN }}
