name: Md.Common.yaml
on:
  push:
    branches:
      - main
    paths:
      - 'Md.Common/**'
      - '.github/workflows/Md.Common.yaml'
  workflow_dispatch:
jobs:
  createSchemaAndTopic:
    uses: MichaelDiers/shared-workflows/.github/workflows/dotnet-nuget.yaml@main
    with:
      projectName: Md.Common
      solutionFolder: Md.Common
    secrets:
      nugetAuthToken: ${{ secrets.NUGET_AUTH_TOKEN }}
