name: Md.GoogleCloudSecrets
on:
  push:
    branches:
      - main
    paths:
      - 'Md.GoogleCloudSecrets/**'
  workflow_dispatch:
jobs:
  buildAndPublishNuget:
    uses: MichaelDiers/shared-workflows/.github/workflows/dotnet-nuget.yaml@main
    with:
      projectName: Md.GoogleCloudSecrets
      solutionFolder: Md.GoogleCloudSecrets
    secrets:
      nugetAuthToken: ${{ secrets.NUGET_AUTH_TOKEN }}
