name: Md.GoogleCloudPubSub.yaml
on:
  push:
    branches:
      - main
    paths:
      - 'Md.GoogleCloudPubSub/**'
      - '.github/workflows/Md.GoogleCloudPubSub.yaml'
  workflow_dispatch:
jobs:
  createSchemaAndTopic:
    uses: MichaelDiers/shared-workflows/.github/workflows/dotnet-nuget.yaml@main
    with:
      projectName: Md.GoogleCloudPubSub
      solutionFolder: Md.GoogleCloudPubSub
    secrets:
      nugetAuthToken: ${{ secrets.NUGET_AUTH_TOKEN }}
