name: Md.GoogleCloudFunctions.yaml
on:
  push:
    branches:
      - main
    paths:
      - 'Md.GoogleCloudFunctions/**'
      - '.github/workflows/Md.GoogleCloudFunctions.yaml'
  workflow_dispatch:
jobs:
  createSchemaAndTopic:
    uses: MichaelDiers/shared-workflows/.github/workflows/dotnet-nuget.yaml@main
    with:
      projectName: Md.GoogleCloudFunctions
      solutionFolder: Md.GoogleCloudFunctions
    secrets:
      nugetAuthToken: ${{ secrets.NUGET_AUTH_TOKEN }}
