name: Md.GoogleCloudFirestore
on:
  push:
    branches:
      - main
    paths:
      - 'Md.GoogleCloudFirestore/**'
  workflow_dispatch:
jobs:
  buildAndPublishNuget:
    uses: MichaelDiers/shared-workflows/.github/workflows/dotnet-nuget.yaml@main
    with:
      projectName: Md.GoogleCloudFirestore
      solutionFolder: Md.GoogleCloudFirestore
    secrets:
      nugetAuthToken: ${{ secrets.NUGET_AUTH_TOKEN }}
