name: Md.GoogleCloudFirestore.yaml
on:
  push:
    branches:
      - main
    paths:
      - 'Md.GoogleCloudFirestore/**'
      - '.github/workflows/Md.GoogleCloudFirestore.yaml'
  workflow_dispatch:
jobs:
  createSchemaAndTopic:
    uses: MichaelDiers/shared-workflows/.github/workflows/dotnet-nuget.yaml@main
    with:
      projectName: Md.GoogleCloudFirestore
      solutionFolder: Md.GoogleCloudFirestore
    secrets:
      nugetAuthToken: ${{ secrets.NUGET_AUTH_TOKEN }}
