name: Md.GoogleCloudFunctions
on:
  push:
    branches:
      - main
    paths:
      - 'Md.GoogleCloudFunctions/**'
  workflow_dispatch:
jobs:
  buildAndPublishNuget:
    uses: MichaelDiers/shared-workflows/.github/workflows/dotnet-nuget.yaml@main
    with:
      projectName: Md.GoogleCloudFunctions
      solutionFolder: Md.GoogleCloudFunctions
    secrets:
      nugetAuthToken: ${{ secrets.NUGET_AUTH_TOKEN }}
