name: Md.GoogleCloudPubSub
on:
  push:
    branches:
      - main
    paths:
      - 'Md.GoogleCloudPubSub/**'
  workflow_dispatch:
jobs:
  buildAndPublishNuget:
    uses: MichaelDiers/shared-workflows/.github/workflows/dotnet-nuget.yaml@main
    with:
      projectName: Md.GoogleCloudPubSub
      solutionFolder: Md.GoogleCloudPubSub
    secrets:
      nugetAuthToken: ${{ secrets.NUGET_AUTH_TOKEN }}
